version: '3'
 
services:
    reverseproxy:
        build: .
        ports:
            - 80:80
            # - 8080:8080
            # - 8081:8081
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
        ports:
            - 780:80
 
    # apache:
    #     depends_on:
    #         - reverseproxy
    #     image: httpd:alpine
    #     restart: always
    #     ports:
    #         - 880:80