version: '3'
 
services:
    reverseproxy:
        build: .
        ports:
            - 80:80
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
        # ports:
        #     - 780:80

    grafana:
        image: grafana/grafana:9.3.0
        ports:
            - 3001:3000
        restart: unless-stopped
        volumes:
        - ./grafana-data:/var/lib/grafana
 