version: '3'
 
services:
    reverseproxy:
        build: .
        ports:
            - 80:80
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
        # ports:
        #     - 780:80
 